WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
DEBUG:discord.client:on_ready has successfully been registered as an event
DEBUG:asyncio:Using selector: EpollSelector
INFO:discord.client:logging in using static token
INFO:discord.gateway:Shard ID None has connected to Gateway (Session ID: 901ad66f7910063a847b7b966c387cfa).
INFO:discord:Logado como Minecraft Bot
ERROR:discord.ext.tasks:Unhandled exception in internal background task 'check_con'.
Traceback (most recent call last):
  File "/home/gabriel/Documents/discord_bot/.venv/lib/python3.10/site-packages/discord/ext/tasks/__init__.py", line 239, in _loop
    await self.coro(*args, **kwargs)
  File "/home/gabriel/Documents/discord_bot/bot.py", line 19, in check_con
    await system.check_connection()
TypeError: System.check_connection() missing 1 required positional argument: 'ping'
ERROR:discord.client:Ignoring exception in on_ready
Traceback (most recent call last):
  File "/home/gabriel/Documents/discord_bot/.venv/lib/python3.10/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/gabriel/Documents/discord_bot/bot.py", line 15, in on_ready
    await check_con.start()
  File "/home/gabriel/Documents/discord_bot/.venv/lib/python3.10/site-packages/discord/ext/tasks/__init__.py", line 264, in _loop
    raise exc
  File "/home/gabriel/Documents/discord_bot/.venv/lib/python3.10/site-packages/discord/ext/tasks/__init__.py", line 239, in _loop
    await self.coro(*args, **kwargs)
  File "/home/gabriel/Documents/discord_bot/bot.py", line 19, in check_con
    await system.check_connection()
TypeError: System.check_connection() missing 1 required positional argument: 'ping'
